import type { Metadata } from 'next';
import localFont from 'next/font/local';
import './globals.css';
import QueryProvider from '@/providers/QueryProvider';
import { Inter } from 'next/font/google';
import { cn } from '@/lib/utils';

const inter = Inter({ subsets: ['latin'], variable: '--font-sans' });

const figtree = localFont({
  src: [
    {
      path: './font/static/Figtree-Light.ttf',
      weight: '300',
      style: 'normal',
    },
    {
      path: './font/static/Figtree-LightItalic.ttf',
      weight: '300',
      style: 'italic',
    },
    {
      path: './font/static/Figtree-Regular.ttf',
      weight: '400',
      style: 'normal',
    },
    {
      path: './font/static/Figtree-Italic.ttf',
      weight: '400',
      style: 'italic',
    },
    {
      path: './font/static/Figtree-Medium.ttf',
      weight: '500',
      style: 'normal',
    },
    {
      path: './font/static/Figtree-MediumItalic.ttf',
      weight: '500',
      style: 'italic',
    },
    {
      path: './font/static/Figtree-SemiBold.ttf',
      weight: '600',
      style: 'normal',
    },
    {
      path: './font/static/Figtree-SemiBoldItalic.ttf',
      weight: '600',
      style: 'italic',
    },
    {
      path: './font/static/Figtree-Bold.ttf',
      weight: '700',
      style: 'normal',
    },
    {
      path: './font/static/Figtree-BoldItalic.ttf',
      weight: '700',
      style: 'italic',
    },
    {
      path: './font/static/Figtree-ExtraBold.ttf',
      weight: '800',
      style: 'normal',
    },
    {
      path: './font/static/Figtree-ExtraBoldItalic.ttf',
      weight: '800',
      style: 'italic',
    },
    {
      path: './font/static/Figtree-Black.ttf',
      weight: '900',
      style: 'normal',
    },
    {
      path: './font/static/Figtree-BlackItalic.ttf',
      weight: '900',
      style: 'italic',
    },
  ],
  variable: '--font-figtree',
  display: 'swap',
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn('font-sans', inter.variable)}>
      <body className={`${figtree.variable} antialiased selection:bg-black selection:text-white`}>
        <QueryProvider>{children}</QueryProvider>
      </body>
    </html>
  );
}
