import {
  SiJavascript,
  SiTypescript,
  SiPython,
  SiC,
  SiCplusplus,

  SiGo,
  SiRust,
  SiRuby,
  SiPhp,
  SiKotlin,
  SiSwift,
  SiDart,
  SiScala,
  SiHaskell,
  SiElixir,
  SiErlang,
  SiLua,
  SiPerl,
  SiR,

  SiJulia,
  SiFortran,

  SiZig,
  SiCrystal,
  SiNim,
  SiSolidity,
  SiV,
  SiFsharp,
  SiOcaml,
  SiReason,
  SiWebassembly,
  SiHtml5,
  SiCss3,
  SiSass,
  SiLess,
  SiTailwindcss,
  SiReact,
  SiNextdotjs,
  SiNodedotjs,
  SiExpress,
  SiVuedotjs,
  SiSvelte,
  SiAngular,
  SiFlutter,
  SiElectron,
  SiGraphql,
  SiFirebase,
  SiSupabase,
  SiMongodb,
  SiPostgresql,
  SiMysql,
  SiRedis,
  SiDocker,
  SiKubernetes,
} from 'react-icons/si';
import { TbBrandCSharp } from "react-icons/tb";
import { FaJava } from "react-icons/fa";


export const LANGICONS = {
  javascript: SiJavascript,
  typescript: SiTypescript,
  python: SiPython,
  java: FaJava,
  c: SiC,
  cpp: SiCplusplus,
  csharp: TbBrandCSharp,
  go: SiGo,
  rust: SiRust,
  ruby: SiRuby,
  php: SiPhp,
  kotlin: SiKotlin,
  swift: SiSwift,
  dart: SiDart,
  scala: SiScala,
  haskell: SiHaskell,
  elixir: SiElixir,
  erlang: SiErlang,
  lua: SiLua,
  perl: SiPerl,
  r: SiR,
  julia: SiJulia,
  fortran: SiFortran,
  zig: SiZig,
  crystal: SiCrystal,
  nim: SiNim,
  solidity: SiSolidity,
  vlang: SiV,
  fsharp: SiFsharp,
  ocaml: SiOcaml,
  reasonml: SiReason,
  webassembly: SiWebassembly,

  html: SiHtml5,
  css: SiCss3,
  sass: SiSass,
  less: SiLess,
  tailwind: SiTailwindcss,

  react: SiReact,
  nextjs: SiNextdotjs,
  nodejs: SiNodedotjs,
  express: SiExpress,
  vue: SiVuedotjs,
  svelte: SiSvelte,
  angular: SiAngular,
  flutter: SiFlutter,
  electron: SiElectron,

  graphql: SiGraphql,
  firebase: SiFirebase,
  supabase: SiSupabase,

  mongodb: SiMongodb,
  postgres: SiPostgresql,
  mysql: SiMysql,
  redis: SiRedis,

  docker: SiDocker,
  kubernetes: SiKubernetes,
};
